version: '3'
services:
  app:
    container_name: docker_node
    build: .
    ports:
      - '80:3000'


  mysql-dev:
    container_name: docker_mysql
    image: mysql:8.0.2
    environment: 
      - 'MYSQL_ROOT_PASSWORD'
      - 'MYSQL_USER'
      - 'MYSQL_PASSWORD'
      - 'MYSQL_DATABASE'
    ports:
      - '3300:3306'


  redis:
    container_name: docker_redis
    image: redis:5.0.7
    ports:
      - '6379:6379'

